
set  -g default-terminal "screen-256color"
set  -g base-index      0
setw -g pane-base-index 0

new-session

set -g status-keys emacs
set -g mode-keys   emacs

# rebind main key: C-j
unbind C-b
set -g prefix C-j
bind -N "Send the prefix key through to the application" \
  j send-prefix
bind C-j last-window

set  -g mouse             on
set  -g focus-events      on
setw -g aggressive-resize on
setw -g clock-mode-style  12
set  -s escape-time       500
set  -g history-limit     50000

set-window-option -g allow-rename off
set-window-option -g automatic-rename off
set-option -g display-time 7000

# Increase tmux messages display duration from 750ms to 4s
set -g display-time 4000

# Refresh 'status-left' and 'status-right' more often, from every 15s to 5s
set -g status-interval 5

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'Nybkox/tmux-kanagawa'
set -g @kanagawa-show-powerline true
set -g @kanagawa-show-flags true
set -g @kanagawa-plugins "git time"
set -g @kanagawa-ignore-window-colors true

run '~/.config/tmux/plugins/tpm-redux/tpm'
